# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0021_auto_20160929_1458'),
        ('mosaico', '0009_template_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='newsletter.Client', verbose_name='client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='inserimento'),
        ),
        migrations.AlterField(
            model_name='template',
            name='key',
            field=models.CharField(max_length=10, verbose_name='chiave'),
        ),
        migrations.AlterField(
            model_name='template',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='ultima modifica'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nome'),
        ),
    ]
