# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosaico', '0010_auto_20160930_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.Client', verbose_name='client'),
        ),
    ]
