# Generated by Django 2.2.2 on 2019-11-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosaico', '0014_template_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='newsletter.Campaign', verbose_name='campagna'),
        ),
    ]
