# Generated by Django 2.2.2 on 2019-11-29 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mosaico', '0015_auto_20191126_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='campaign',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.Campaign', verbose_name='campagna'),
        ),
    ]
