##
# Remote playobook
# - Installation of required packages
# - Db installation and creation, user db creation and privileges granted
# - Web app initialization (user nd dirs creation)
##
---
- hosts: staging
  user: root
  vars:
    repo_name: tazebao
    core_name: core
  pre_tasks:
    - name: update apt cache
      become: true
      become_method: sudo
      apt: update_cache=yes
  roles:
    - common
    - database
    - webapp
    - webserver
