# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('insertion_datetime', models.DateTimeField(auto_now_add=True, verbose_name='inserimento')),
                ('last_edit_datetime', models.DateTimeField(auto_now=True, verbose_name='ultima modifica')),
                ('subject', models.CharField(max_length=255, verbose_name='oggetto')),
                ('plain_text', models.TextField(blank=True, null=True, verbose_name='testo')),
                ('html_text', models.TextField(blank=True, null=True, verbose_name='testo html')),
                ('view_online', models.BooleanField(verbose_name='visualizza online')),
            ],
            options={
                'verbose_name': 'Campagna',
                'verbose_name_plural': 'Campagne',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('domain', models.CharField(max_length=100, verbose_name='dominio')),
                ('id_key', models.CharField(blank=True, max_length=8, null=True, unique=True, verbose_name='id key')),
                ('secret_key', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='secret key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utente')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.BooleanField(default=False, verbose_name='errore')),
                ('success', models.BooleanField(default=False, verbose_name='successo')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Campaign', verbose_name='campagna')),
            ],
            options={
                'verbose_name': 'Invio',
                'verbose_name_plural': 'Invii',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('subscription_datetime', models.DateTimeField(auto_now_add=True, verbose_name='data sottoscrizione')),
                ('info', models.TextField(blank=True, null=True, verbose_name='info')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'Iscritto',
                'verbose_name_plural': 'Iscritti',
            },
        ),
        migrations.CreateModel(
            name='SubscriberList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'Lista iscritti',
                'verbose_name_plural': 'Liste iscritti',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('sending_address', models.EmailField(max_length=254, verbose_name='indirizzo invio')),
                ('sending_name', models.CharField(max_length=50, verbose_name='nome invio')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topic',
            },
        ),
        migrations.AddField(
            model_name='subscriber',
            name='lists',
            field=models.ManyToManyField(to='newsletter.SubscriberList', verbose_name='liste'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='lists',
            field=models.ManyToManyField(to='newsletter.SubscriberList', verbose_name='liste'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Client', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.Topic'),
        ),
        migrations.CreateModel(
            name='UserCampaign',
            fields=[
            ],
            options={
                'verbose_name': 'User - Campagna',
                'proxy': True,
                'verbose_name_plural': 'User - Campagne',
            },
            bases=('newsletter.campaign',),
        ),
        migrations.CreateModel(
            name='UserClient',
            fields=[
            ],
            options={
                'verbose_name': 'User - Client',
                'proxy': True,
                'verbose_name_plural': 'User - Client',
            },
            bases=('newsletter.client',),
        ),
        migrations.CreateModel(
            name='UserSubscriber',
            fields=[
            ],
            options={
                'verbose_name': 'User - Iscritto',
                'proxy': True,
                'verbose_name_plural': 'User - Iscritti',
            },
            bases=('newsletter.subscriber',),
        ),
        migrations.CreateModel(
            name='UserSubscriberList',
            fields=[
            ],
            options={
                'verbose_name': 'User - Lista iscritti',
                'proxy': True,
                'verbose_name_plural': 'User - Liste iscritti',
            },
            bases=('newsletter.subscriberlist',),
        ),
        migrations.CreateModel(
            name='UserTopic',
            fields=[
            ],
            options={
                'verbose_name': 'User - Topic',
                'proxy': True,
                'verbose_name_plural': 'User - Topic',
            },
            bases=('newsletter.topic',),
        ),
    ]
