# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='newsletter.Topic'),
            preserve_default=False,
        ),
    ]
