# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20160909_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='sent',
            field=models.IntegerField(blank=True, null=True, verbose_name='e-mail inviate'),
        ),
    ]
