# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_dispatch_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='sent_recipients',
            field=models.TextField(blank=True, null=True, verbose_name='indirizzi'),
        ),
    ]
