# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_dispatch_sent_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='error_recipients',
            field=models.TextField(blank=True, null=True, verbose_name='indirizzi in errore'),
        ),
    ]
