# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_dispatch_error_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDispatch',
            fields=[
            ],
            options={
                'verbose_name': 'User - Invio Campagna',
                'proxy': True,
                'verbose_name_plural': 'User - Invii Campagne',
            },
            bases=('newsletter.dispatch',),
        ),
    ]
