# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0002_mailermessage_reply_to'),
        ('newsletter', '0008_auto_20160912_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMailerMessage',
            fields=[
            ],
            options={
                'verbose_name': 'User - Log coda di invio',
                'proxy': True,
                'verbose_name_plural': 'User - Log code di invio',
            },
            bases=('mailqueue.mailermessage',),
        ),
    ]
