# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_auto_20160920_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='unsubscription_text',
        ),
        migrations.AddField(
            model_name='campaign',
            name='show_unsubscribe_text',
            field=models.BooleanField(default=True, verbose_name='mostra testo cancellazione sottoscrizione'),
        ),
        migrations.AddField(
            model_name='topic',
            name='unsubscription_html_text',
            field=models.TextField(blank=True, help_text='\n            <p><b>variabili</b> disponibili</p>\n            - <code>{{ id }}</code> id iscritto<br />\n            - <code>{{ email }}</code> e-mail iscritto<br />\n            - <code>{{ subscription_datetime }}</code> data\n                            sottoscrizione<br />\n            <p>Per criptare utilizzando la SECRET_KEY:</p>\n            <code>{% encrypt id email %}</code>\n            <p>genera una stringa criptata della concatenazione di id\n                            e email.</p>\n        ', null=True, verbose_name='testo html cancellazione registrazione'),
        ),
        migrations.AddField(
            model_name='topic',
            name='unsubscription_text',
            field=models.TextField(blank=True, help_text='\n            <p><b>variabili</b> disponibili</p>\n            - <code>{{ id }}</code> id iscritto<br />\n            - <code>{{ email }}</code> e-mail iscritto<br />\n            - <code>{{ subscription_datetime }}</code> data\n                            sottoscrizione<br />\n            <p>Per criptare utilizzando la SECRET_KEY:</p>\n            <code>{% encrypt id email %}</code>\n            <p>genera una stringa criptata della concatenazione di id\n                            e email.</p>\n        ', null=True, verbose_name='testo cancellazione registrazione'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='plain_text',
            field=models.TextField(blank=True, help_text="\n            <p><b>variabili</b> disponibili per il testo e testo html\n                            se la campagna \xe8 visualizzabile online:</p>\n            - <code>{{ view_online_url }}</code> url relativo della newsletter\n                 online<br />\n            - <code>{{ site_url }}</code> url applicazione senza\n                 protocollo<br />\n            per ottenere l'url completo della newsletter online<br />\n            <code>http://{{ site_url }}{{ view_online_url }}</code>\n        ", null=True, verbose_name='testo'),
        ),
    ]
