# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_auto_20160921_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='show_unsubscribe_text',
        ),
    ]
