# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0012_remove_campaign_show_unsubscribe_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apertura',
                'verbose_name_plural': 'Aperture',
            },
        ),
        migrations.AlterModelOptions(
            name='dispatch',
            options={},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='html_text',
            field=models.TextField(blank=True, help_text='si possono utilizzare le stesse variabili definite sopra\n        ', null=True, verbose_name='testo html'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='plain_text',
            field=models.TextField(blank=True, help_text="\n            <p><b>variabili</b> disponibili per il testo e testo html:</p>\n            - <code>{{ id }}</code> id campagna<br />\n            - <code>{{ unsubscription_text }}</code> testo cancellazione\n                            sottoscrizione definito nel Topic<br />\n            - <code>{{ view_online_url }}</code> url relativo della newsletter\n                 online<br />\n            - <code>{{ site_url }}</code> url applicazione senza\n                 protocollo<br />\n            per ottenere l'url completo della newsletter online<br />\n            <code>http://{{ site_url }}{{ view_online_url }}</code>\n        ", null=True, verbose_name='testo'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fine'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='started_at',
            field=models.DateTimeField(verbose_name='inizio'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='unsubscription_html_text',
            field=models.TextField(blank=True, help_text='\n            <p><b>variabili</b> disponibili</p>\n            - <code>{{ id }}</code> id iscritto<br />\n            - <code>{{ email }}</code> e-mail iscritto<br />\n            - <code>{{ subscription_datetime }}</code> data\n                            sottoscrizione<br />\n            <p>Per criptare utilizzando la SECRET_KEY:</p>\n            <code>{% encrypt id email %}</code>\n            <p>genera una stringa criptata ed url encoded della\n                            concatenazione di id e email.</p>\n        ', null=True, verbose_name='testo html cancellazione registrazione'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Dispatch', verbose_name='invio'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Subscriber', verbose_name='iscritto'),
        ),
    ]
