# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0013_auto_20160926_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTracking',
            fields=[
            ],
            options={
                'verbose_name': 'User - Traking',
                'proxy': True,
                'verbose_name_plural': 'User - Tracking',
            },
            bases=('newsletter.dispatch',),
        ),
    ]
