# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0016_usertracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatch',
            options={'verbose_name': 'Invio', 'verbose_name_plural': 'Invii'},
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'verbose_name': 'Tracking', 'verbose_name_plural': 'Tracking'},
        ),
        migrations.AddField(
            model_name='dispatch',
            name='statistics',
            field=models.BooleanField(default=False, verbose_name='statistiche'),
        ),
    ]
