# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0018_tracking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='note'),
        ),
    ]
