# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0019_tracking_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='statistics',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='click_statistics',
            field=models.BooleanField(default=False, verbose_name='statistiche click'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='open_statistics',
            field=models.BooleanField(default=False, verbose_name='statistiche apertura'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='html_text',
            field=models.TextField(blank=True, help_text="\n            <p><b>Variabili</b> disponibili per il testo e testo html:</p>\n            - <code>{{ id }}</code> id campagna<br />\n            - <code>{{ unsubscription_text }}</code> testo cancellazione\n                            sottoscrizione definito nel Topic<br />\n            - <code>{{ view_online_url }}</code> url relativo della newsletter\n                 online<br />\n            - <code>{{ site_url }}</code> url applicazione senza\n                 protocollo<br />\n            per ottenere l'url completo della newsletter online<br />\n            <code>http://{{ site_url }}{{ view_online_url }}</code>\n            <p>Per creare un link con tracciamento del click:</p>\n            <code>{% link 'http://www.example.com' %}</code>\n            <p>genera un url che se visitato tiene traccia dell'evento e\n            ridirige su http://www.example.com.</p>\n        ", null=True, verbose_name='testo html'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='plain_text',
            field=models.TextField(blank=True, help_text="\n            <p><b>Variabili</b> disponibili per il testo e testo html:</p>\n            - <code>{{ id }}</code> id campagna<br />\n            - <code>{{ unsubscription_text }}</code> testo cancellazione\n                            sottoscrizione definito nel Topic<br />\n            - <code>{{ view_online_url }}</code> url relativo della newsletter\n                 online<br />\n            - <code>{{ site_url }}</code> url applicazione senza\n                 protocollo<br />\n            per ottenere l'url completo della newsletter online<br />\n            <code>http://{{ site_url }}{{ view_online_url }}</code>\n            <p>Per creare un link con tracciamento del click:</p>\n            <code>{% link 'http://www.example.com' %}</code>\n            <p>genera un url che se visitato tiene traccia dell'evento e\n            ridirige su http://www.example.com.</p>\n        ", null=True, verbose_name='testo'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='unsubscription_html_text',
            field=models.TextField(blank=True, help_text='\n            <p><b>Variabili</b> disponibili</p>\n            - <code>{{ id }}</code> id iscritto<br />\n            - <code>{{ email }}</code> e-mail iscritto<br />\n            - <code>{{ subscription_datetime }}</code> data\n                            sottoscrizione<br />\n            <p>Per criptare utilizzando la SECRET_KEY:</p>\n            <code>{% encrypt id email %}</code>\n            <p>genera una stringa criptata ed url encoded della\n                            concatenazione di id e email.</p>\n        ', null=True, verbose_name='testo html cancellazione registrazione'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='unsubscription_text',
            field=models.TextField(blank=True, help_text='\n            <p><b>Variabili</b> disponibili</p>\n            - <code>{{ id }}</code> id iscritto<br />\n            - <code>{{ email }}</code> e-mail iscritto<br />\n            - <code>{{ subscription_datetime }}</code> data\n                            sottoscrizione<br />\n            <p>Per criptare utilizzando la SECRET_KEY:</p>\n            <code>{% encrypt id email %}</code>\n            <p>genera una stringa criptata della concatenazione di id\n                            e email.</p>\n        ', null=True, verbose_name='testo cancellazione registrazione'),
        ),
    ]
