# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0021_auto_20160929_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='unsubscription_text',
            new_name='unsubscription_url',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='unsubscription_html_text',
        ),
    ]
