# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0022_auto_20160930_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='unsubscription_url',
            field=models.CharField(blank=True, help_text='\n            <p><b>Variabili</b> disponibili</p>\n            - <code>{{ id }}</code> id iscritto<br />\n            - <code>{{ email }}</code> e-mail iscritto<br />\n            - <code>{{ subscription_datetime }}</code> data\n                            sottoscrizione<br />\n            <p>Per criptare utilizzando la SECRET_KEY:</p>\n            <code>{% encrypt id email %}</code>\n            <p>genera una stringa criptata della concatenazione di id\n                            e email.</p>\n        ', max_length=255, null=True, verbose_name='url cancellazione registrazione'),
        ),
    ]
