# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0023_auto_20160930_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='unsubscription_url',
            new_name='unsubscribe',
        ),
    ]
