# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0024_auto_20160930_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='unsubscribe',
            new_name='unsubscribe_url',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='html_text',
            field=models.TextField(blank=True, help_text="\n            <p><b>Variabili</b> disponibili per il testo e testo html:</p>\n            - <code>{{ id }}</code> id campagna<br />\n            - <code>{{ unsubscribe_url }}</code> url cancellazione\n                            sottoscrizione definito nel Topic<br />\n            - <code>{{ view_online_url }}</code> url assoluto della newsletter\n                 online<br />\n            - <code>{{ domain }}</code> dominio applicazione</p>\n            <p>Per creare un link con tracciamento del click:<br />\n            <code>{% link 'http://www.example.com' %}</code><br />\n            genera un url che se visitato tiene traccia dell'evento e\n            ridirige su http://www.example.com.</p>\n        ", null=True, verbose_name='testo html'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='plain_text',
            field=models.TextField(blank=True, help_text="\n            <p><b>Variabili</b> disponibili per il testo e testo html:</p>\n            - <code>{{ id }}</code> id campagna<br />\n            - <code>{{ unsubscribe_url }}</code> url cancellazione\n                            sottoscrizione definito nel Topic<br />\n            - <code>{{ view_online_url }}</code> url assoluto della newsletter\n                 online<br />\n            - <code>{{ domain }}</code> dominio applicazione<br />\n            <p>Per creare un link con tracciamento del click:<br />\n            <code>{% link 'http://www.example.com' %}</code><br />\n            genera un url che se visitato tiene traccia dell'evento e\n            ridirige su http://www.example.com.</p>\n        ", null=True, verbose_name='testo'),
        ),
    ]
