# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-29 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0025_auto_20161004_1259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCampaign',
        ),
        migrations.DeleteModel(
            name='UserClient',
        ),
        migrations.DeleteModel(
            name='UserDispatch',
        ),
        migrations.DeleteModel(
            name='UserSubscriber',
        ),
        migrations.DeleteModel(
            name='UserSubscriberList',
        ),
        migrations.DeleteModel(
            name='UserTopic',
        ),
        migrations.DeleteModel(
            name='UserTracking',
        ),
        migrations.AlterModelOptions(
            name='usermailermessage',
            options={'verbose_name': 'Log invio', 'verbose_name_plural': 'Log invii'},
        ),
        migrations.AddField(
            model_name='subscriber',
            name='opt_in',
            field=models.BooleanField(default=False, verbose_name='accettazione GDPR'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='opt_in_datetime',
            field=models.BooleanField(default=True, verbose_name='data accettazione GDPR'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='html_text',
            field=models.TextField(blank=True, help_text="\n            <p><b>Variabili</b> disponibili per il testo e testo html:</p>\n            <p>\n            - <code>{{ id }}</code> id campagna<br />\n            - <code>{{ unsubscribe_url }}</code> url cancellazione\n                            sottoscrizione definito nel Topic<br />\n            - <code>{{ view_online_url }}</code> url assoluto della newsletter\n                 online<br />\n            - <code>{{ domain }}</code> dominio applicazione</p>\n            - <code>{{ email }}</code> e-mail iscritto<br />\n            </p>\n            <p>Per criptare utilizzando la SECRET_KEY:<br />\n            <code>{% encrypt email %}</code><br />\n            genera una stringa criptata della email.</p>\n            <p>Per creare un link con tracciamento del click:<br />\n            <code>{% link 'http://www.example.com' %}</code><br />\n            genera un url che se visitato tiene traccia dell'evento e\n            ridirige su http://www.example.com.</p>\n        ", null=True, verbose_name='testo html'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='plain_text',
            field=models.TextField(blank=True, help_text="\n            <p><b>Variabili</b> disponibili per il testo e testo html:</p>\n            <p>\n            - <code>{{ id }}</code> id campagna<br />\n            - <code>{{ unsubscribe_url }}</code> url cancellazione\n                            sottoscrizione definito nel Topic<br />\n            - <code>{{ view_online_url }}</code> url assoluto della newsletter\n                 online<br />\n            - <code>{{ domain }}</code> dominio applicazione<br />\n            - <code>{{ email }}</code> e-mail iscritto<br />\n            </p>\n            <p>Per criptare utilizzando la SECRET_KEY:<br />\n            <code>{% encrypt email %}</code><br />\n            genera una stringa criptata della email.</p>\n            <p>Per creare un link con tracciamento del click:<br />\n            <code>{% link 'http://www.example.com' %}</code><br />\n            genera un url che se visitato tiene traccia dell'evento e\n            ridirige su http://www.example.com.</p>\n        ", null=True, verbose_name='testo'),
        ),
    ]
