# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-29 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0026_auto_20180529_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='opt_in_datetime',
        ),
    ]
