# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-05-29 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0027_remove_subscriber_opt_in_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='opt_in_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data accettazione GDPR'),
        ),
    ]
