# Generated by Django 2.2.2 on 2019-06-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0028_subscriber_opt_in_datetime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('-id',), 'verbose_name': 'Campagna', 'verbose_name_plural': 'Campagne'},
        ),
    ]
