# Generated by Django 2.2.2 on 2019-06-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0029_auto_20190605_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='messaggio di errore'),
        ),
    ]
