# Generated by Django 2.2.2 on 2019-06-07 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0030_dispatch_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField(verbose_name='data e ora')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Campaign', verbose_name='campagna')),
                ('lists', models.ManyToManyField(to='newsletter.SubscriberList', verbose_name='liste')),
            ],
            options={
                'verbose_name': 'Planning',
                'verbose_name_plural': 'Planning',
            },
        ),
    ]
