# Generated by Django 2.2.2 on 2019-06-18 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0032_planning_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='data e ora')),
                ('from_email', models.EmailField(max_length=254, verbose_name='indirizzo from')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='status')),
                ('email_id', models.CharField(max_length=50, verbose_name='id email')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Client', verbose_name='client')),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.Dispatch', verbose_name='invio')),
            ],
            options={
                'verbose_name': 'E-mail fallita',
                'verbose_name_plural': 'E-mail fallite',
            },
        ),
    ]
