# Generated by Django 2.2.2 on 2019-06-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0034_auto_20190618_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('-id',), 'verbose_name': 'campagna', 'verbose_name_plural': 'campagne'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'client', 'verbose_name_plural': 'client'},
        ),
        migrations.AlterModelOptions(
            name='dispatch',
            options={'verbose_name': 'invio', 'verbose_name_plural': 'invii'},
        ),
        migrations.AlterModelOptions(
            name='failedemail',
            options={'verbose_name': 'bounce', 'verbose_name_plural': 'bounces'},
        ),
        migrations.AlterModelOptions(
            name='planning',
            options={'verbose_name': 'planning', 'verbose_name_plural': 'planning'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('email',), 'verbose_name': 'iscritto', 'verbose_name_plural': 'iscritti'},
        ),
        migrations.AlterModelOptions(
            name='subscriberlist',
            options={'verbose_name': 'lista iscritti', 'verbose_name_plural': 'liste iscritti'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'topic', 'verbose_name_plural': 'topic'},
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'verbose_name': 'tracking', 'verbose_name_plural': 'tracking'},
        ),
        migrations.AlterModelOptions(
            name='usermailermessage',
            options={'verbose_name': 'log invio', 'verbose_name_plural': 'log invii'},
        ),
        migrations.AlterField(
            model_name='failedemail',
            name='email_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='id email'),
        ),
    ]
