# Generated by Django 2.2.2 on 2019-10-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0035_auto_20190618_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedemail',
            name='dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bounces', to='newsletter.Dispatch', verbose_name='invio'),
        ),
        migrations.AlterField(
            model_name='failedemail',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bounces', to='newsletter.Subscriber', verbose_name='iscritto'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='newsletter.Dispatch', verbose_name='invio'),
        ),
    ]
