# Generated by Django 2.2.2 on 2019-11-29 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0036_auto_20191018_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='data e ora')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'disiscrizione',
                'verbose_name_plural': 'disiscrizioni',
            },
        ),
    ]
