# Generated by Django 2.2.2 on 2019-11-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0037_unsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsubscription',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data e ora'),
        ),
    ]
