# Generated by Django 2.2.2 on 2023-03-01 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0039_dispatch_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='unsubscribe_url',
            field=models.CharField(blank=True, help_text='\n            <p><b>Variabili</b> disponibili:</p>\n            <p>\n            <ul>\n            <li><code>{{ id }}</code> id iscritto</li>\n            <li><code>{{ email }}</code> e-mail iscritto</li>\n            <li><code>{{ subscription_datetime }}</code> data\n                            sottoscrizione</li>\n            </ul>\n            <p>Per criptare utilizzando la SECRET_KEY:</p>\n            <code>{% encrypt id email %}</code>\n            <p>genera una stringa criptata della concatenazione di id\n                            e email.</p>\n            <p>Se vuoi avere tutto quanto gestito da Tazebao (la disiscrizione avverrà sul dominio Tazebao), inserisci questo URL:</p>\n            <p><code>https://www.tazebao.email/newsletter/unsubscribe/?id={{ id }}&email={{ email }}&sig={% encrypt id email %}</code></p>\n        ', max_length=255, null=True, verbose_name='url cancellazione registrazione'),
        ),
        migrations.CreateModel(
            name='SubscriptionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='data creazione')),
                ('last_edited', models.DateTimeField(auto_now=True, verbose_name='data ultima modifica')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='titolo')),
                ('content', models.TextField(blank=True, null=True, verbose_name='contenuto')),
                ('privacy_disclaimer', models.TextField(verbose_name='disclaimer privacy')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'form sottoscrizione',
                'verbose_name_plural': 'form sottoscrizione',
            },
        ),
    ]
