# Generated by Django 2.2.2 on 2023-03-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0042_remove_subscriptionform_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionform',
            name='lists',
            field=models.ManyToManyField(to='newsletter.SubscriberList', verbose_name='liste'),
        ),
    ]
