# Generated by Django 2.2.2 on 2023-03-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0043_subscriptionform_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionform',
            name='error_url',
            field=models.URLField(default='', verbose_name='URL iscrizione fallita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionform',
            name='success_url',
            field=models.URLField(default='', verbose_name='URL iscrizione eseguita'),
            preserve_default=False,
        ),
    ]
