# Generated by Django 2.2.2 on 2023-03-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0044_auto_20230301_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionform',
            name='error_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL iscrizione fallita'),
        ),
        migrations.AlterField(
            model_name='subscriptionform',
            name='success_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL iscrizione eseguita'),
        ),
    ]
