# Generated by Django 2.2.2 on 2023-03-02 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0045_auto_20230301_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionform',
            name='title',
        ),
    ]
