# Generated by Django 2.2.2 on 2023-07-27 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0046_remove_subscriptionform_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='data e ora')),
                ('question', models.TextField(verbose_name='domanda')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Subscriber', verbose_name='client')),
            ],
            options={
                'verbose_name': 'richiesta suggerimento',
                'verbose_name_plural': 'richieste suggerimenti',
            },
        ),
    ]
