# Generated by Django 2.2.2 on 2023-07-27 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0048_subscriber_suggestions_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='suggestions_per_day',
        ),
    ]
