# Generated by Django 2.2.2 on 2023-07-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0049_remove_subscriber_suggestions_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='suggestions_per_day',
            field=models.IntegerField(default=3, verbose_name='suggerimenti giornalieri'),
        ),
    ]
