# Generated by Django 2.2.2 on 2023-07-27 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0051_remove_suggestionrequest_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionrequest',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newsletter.Client', verbose_name='client'),
            preserve_default=False,
        ),
    ]
