# Generated by Django 2.2.2 on 2023-07-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0052_suggestionrequest_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestionrequest',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='risposta'),
        ),
    ]
