# Generated by Django 2.2.2 on 2023-07-27 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0053_suggestionrequest_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('html', models.TextField(verbose_name='html')),
                ('clients', models.ManyToManyField(blank=True, help_text='Se vuoto viene inviato a tutti', to='newsletter.Client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'messaggio di sistema',
                'verbose_name_plural': 'messaggi di sistema',
            },
        ),
        migrations.CreateModel(
            name='SystemMessageRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.Client', verbose_name='client')),
                ('system_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.SystemMessage', verbose_name='messaggio di sistema')),
            ],
            options={
                'verbose_name': 'letture messaggio di sistema',
                'verbose_name_plural': 'letture messaggi di sistema',
            },
        ),
    ]
